# Generated by Django 6.0.7 on 2026-07-08 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('password', models.CharField(max_length=255)),
                ('birthdate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('link_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('original_url', models.URLField(max_length=255)),
                ('short_url', models.URLField(max_length=255)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('visits', models.BigIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='link.user')),
            ],
        ),
    ]
